[workspace]
members = ["duktape-sys", "duktape", "paclib", "paceval"]

[package]
name = "proxydetox"
version = "0.2.1"
edition = "2018"
homepage = "https://github.com/kiron1/proxydetox"

[dependencies]
base64 = "0.12"
dirs = "2.0"
env_logger = "0.7"
futures-util = { version = "0.3", default-features = false }
http = "0.2"
hyper = "0.13"
log ="0.4"
netrc = { git = "https://github.com/kiron1/netrc-rs", branch = "modernize" }
paclib = { path = "paclib" }
structopt = "0.3"
tokio = { version = "0.2", features = ["full"] }
